/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;

/**
 *
 * @author EGGzin
 */

import conexao.Conexao;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
        
public class frm1 extends javax.swing.JInternalFrame {
    
    Conexao con;

    /**
     * Creates new form frm1
     */
    public frm1() {
        initComponents();
        
        con = new Conexao();
        con.conecta();
        con.executaSQL("select * from registro order by IdReg");       
        preencherTabela();
        posicionarRegistro();
        Tabela.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        txt_Nome = new javax.swing.JTextField();
        txt_DataNasc = new javax.swing.JTextField();
        txt_LocalNasc = new javax.swing.JTextField();
        txt_Curso = new javax.swing.JTextField();
        txt_Serie = new javax.swing.JTextField();

        setBorder(null);
        setClosable(true);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "DataNasc", "LocalNasc", "Curso", "Série"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_LocalNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_DataNasc, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                .addComponent(txt_Nome))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_Curso)
                                .addComponent(txt_Serie)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_DataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_LocalNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        public void preencherTabela(){
        
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        modelo.setNumRows(0);
        
        try {
            
            con.resultset.beforeFirst();
            while(con.resultset.next()){
                
                modelo.addRow(new Object[]{
                    con.resultset.getString("Nome"),
                    con.resultset.getString("DataNasc"),
                    con.resultset.getString("LocalNasc"),
                    con.resultset.getString("Curso"),
                    con.resultset.getString("Série")
                });
                
            }
        
            
            
        }catch(SQLException erro){
    
            JOptionPane.showMessageDialog(null,"\n Erro ao listar dados da tabela!! :\n "+erro,"Mensagem doPrograma",JOptionPane.INFORMATION_MESSAGE);
    
        }
    }

        public void posicionarRegistro(){
        
        try {
            
            con.resultset.first();
            mostrar_Dados();
            
            
        }
        catch (SQLException erro){
            
            JOptionPane.showMessageDialog(null,"Não foi possível posicionar no primeiro registro: "+erro,"Mensagem do Programa",JOptionPane.INFORMATION_MESSAGE);
            
        }
        
    }
        
        public void mostrar_Dados(){
        
        try{
            
            txt_Nome.setText(con.resultset.getString("Nome"));
            txt_DataNasc.setText(con.resultset.getString("DataNasc"));
            txt_LocalNasc.setText(con.resultset.getString("LocalNasc"));
            txt_Curso.setText(con.resultset.getString("Curso"));
            txt_Serie.setText(con.resultset.getString("Série"));
            
        }
        catch (SQLException erro){
            
            JOptionPane.showMessageDialog(null,"Não localizou dados: "+erro,"Mensagemdo Programa",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_Curso;
    private javax.swing.JTextField txt_DataNasc;
    private javax.swing.JTextField txt_LocalNasc;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Serie;
    // End of variables declaration//GEN-END:variables
}
