/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package controle;

/**
 *
 * @author jajps
 */
import conexao.Conexao;
import java.sql.*;
import javax.swing.*;
public class frm7 extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm2
     */
    Conexao con;
    int id;
    public frm7() {
        initComponents();
        con = new Conexao();
        con.conecta();
        con.executaSQL("select * from registro order by IdReg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_Frm3 = new javax.swing.JPanel();
        lbl_Title = new javax.swing.JLabel();
        lbl_prg4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_MelhorProf = new javax.swing.JTextArea();
        lbl_prg1 = new javax.swing.JLabel();
        btn_Next = new javax.swing.JButton();
        lbl_prg2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_PrepVestibular = new javax.swing.JTextArea();
        lbl_prg3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_QualidadeProf = new javax.swing.JTextArea();
        lbl_pagina = new javax.swing.JLabel();
        btn_Sair = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_OuvirMotivado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        pan_Frm3.setBackground(new java.awt.Color(51, 51, 51));

        lbl_Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_Title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Title.setText("Questionario:");

        lbl_prg4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prg4.setText("CITE 3 COISAS QUE OS PROFESSORES EM GERAL PRECISAM MELHORAR:");

        txt_MelhorProf.setColumns(20);
        txt_MelhorProf.setRows(5);
        jScrollPane3.setViewportView(txt_MelhorProf);

        lbl_prg1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prg1.setText("SE VOCÊ FOSSE MAIS OUVIDO SOBRE AS DECISÕES IMPORTANTES DA ESCOLA");

        btn_Next.setBackground(new java.awt.Color(51, 51, 51));
        btn_Next.setForeground(new java.awt.Color(255, 255, 255));
        btn_Next.setText("Próximo");
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        lbl_prg2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prg2.setText("O QUANTO VOCÊ ACHA QUE A ESCOLA TE PREPARA PARA OS VESTIBULARES (DE 0 A 10)? JUSTIFIQUE?");

        txt_PrepVestibular.setColumns(20);
        txt_PrepVestibular.setRows(5);
        jScrollPane1.setViewportView(txt_PrepVestibular);

        lbl_prg3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_prg3.setText("CITE 3 QUALIDADES QUE UM BOM PROFESSOR PRECISA TER:");

        txt_QualidadeProf.setColumns(20);
        txt_QualidadeProf.setRows(5);
        jScrollPane2.setViewportView(txt_QualidadeProf);

        lbl_pagina.setText("6/8");

        btn_Sair.setBackground(new java.awt.Color(51, 51, 51));
        btn_Sair.setText("X");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        txt_OuvirMotivado.setColumns(20);
        txt_OuvirMotivado.setRows(5);
        jScrollPane4.setViewportView(txt_OuvirMotivado);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VOCÊ ACHA QUE FICARIA MAIS MOTIVADO?");

        javax.swing.GroupLayout pan_Frm3Layout = new javax.swing.GroupLayout(pan_Frm3);
        pan_Frm3.setLayout(pan_Frm3Layout);
        pan_Frm3Layout.setHorizontalGroup(
            pan_Frm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pan_Frm3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Sair)
                .addContainerGap())
            .addGroup(pan_Frm3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pan_Frm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_prg1)
                    .addGroup(pan_Frm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pan_Frm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_prg3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_prg4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_prg2))
                        .addGroup(pan_Frm3Layout.createSequentialGroup()
                            .addComponent(btn_Next)
                            .addGap(18, 18, 18)
                            .addComponent(lbl_pagina)))
                    .addGroup(pan_Frm3Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lbl_Title)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        pan_Frm3Layout.setVerticalGroup(
            pan_Frm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_Frm3Layout.createSequentialGroup()
                .addComponent(btn_Sair)
                .addGap(3, 3, 3)
                .addComponent(lbl_Title)
                .addGap(33, 33, 33)
                .addComponent(lbl_prg1)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(lbl_prg2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lbl_prg3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lbl_prg4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pan_Frm3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_pagina)
                    .addComponent(btn_Next))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_Frm3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pan_Frm3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        //        String nome = txt_Nome.getText();
        //        String curso = txt_Curso.getText();
        //        String data = txt_DataNasc.getText();
        //        String serie = txt_Serie.getText();
        //        String nascLocal = txt_LocalNasc.getText();
        //
        //        //atribui valores aos campos baseando-se nas variaveis
        //        try {
            //            String insert_sql = "insert into registro (Nome,DataNasc, LocalNasc, Curso, Serie"
            //                    + ") values ('" + nome + "','" + data + "','"
            //                    + nascLocal + "','" + curso
            //                    + "','" + serie + "')";
            //            con.statement.executeUpdate(insert_sql);
            //            JOptionPane.showMessageDialog(null,
                //                    "Gravação realizada com sucesso!!", "Mensagem do Programa",
                //                    JOptionPane.INFORMATION_MESSAGE);
            //            frm2 form2 = new frm2();
            //            getParent().add(form2);
            //            form2.setVisible(true);
            //            dispose();
            //
            //        } catch (SQLException errosql) {
            //            JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n"
                //                    + errosql, "Mensagem do Programa",
                //                    JOptionPane.INFORMATION_MESSAGE);
            //        }
    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_SairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lbl_Title;
    private javax.swing.JLabel lbl_pagina;
    private javax.swing.JLabel lbl_prg1;
    private javax.swing.JLabel lbl_prg2;
    private javax.swing.JLabel lbl_prg3;
    private javax.swing.JLabel lbl_prg4;
    private javax.swing.JPanel pan_Frm3;
    private javax.swing.JTextArea txt_MelhorProf;
    private javax.swing.JTextArea txt_OuvirMotivado;
    private javax.swing.JTextArea txt_PrepVestibular;
    private javax.swing.JTextArea txt_QualidadeProf;
    // End of variables declaration//GEN-END:variables
}
