/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

/**
 *
 * @author EGGzin
 */

import javax.swing.*;
import java.awt.*;
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/images/Background.png"));
        Image image = icon.getImage();
        Workspace = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        toolBar = new javax.swing.JToolBar(){

            public void paintComponent(Graphics g){
                g.setColor(new Color(48,50,52));
                g.fillRect(0,0,getWidth(),getHeight());
            }

        };
        btn_Logar = new javax.swing.JButton();
        btn_Quest = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar(){

            public void paintComponent(Graphics g){
                g.setColor(new Color(48,50,52));
                g.fillRect(0,0,getWidth(),getHeight());
            }

        };
        menuItem_Quest = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuItem_Devs = new javax.swing.JMenu();
        menuItem_Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        toolBar.setBackground(new java.awt.Color(51, 51, 51));
        toolBar.setBorder(null);
        toolBar.setOrientation(javax.swing.SwingConstants.VERTICAL);
        toolBar.setEnabled(false);
        toolBar.setFocusable(false);

        btn_Logar.setBackground(new java.awt.Color(51, 51, 51));
        btn_Logar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Logar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLogar.png"))); // NOI18N
        btn_Logar.setFocusable(false);
        btn_Logar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Logar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LogarActionPerformed(evt);
            }
        });
        toolBar.add(btn_Logar);

        btn_Quest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnQuest.png"))); // NOI18N
        btn_Quest.setFocusable(false);
        btn_Quest.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Quest.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Quest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuestActionPerformed(evt);
            }
        });
        toolBar.add(btn_Quest);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Workspace.setLayer(toolBar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Workspace.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout WorkspaceLayout = new javax.swing.GroupLayout(Workspace);
        Workspace.setLayout(WorkspaceLayout);
        WorkspaceLayout.setHorizontalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkspaceLayout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 727, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        WorkspaceLayout.setVerticalGroup(
            WorkspaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
            .addGroup(WorkspaceLayout.createSequentialGroup()
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Menu.setBorder(null);

        menuItem_Quest.setBackground(new java.awt.Color(51, 51, 51));
        menuItem_Quest.setForeground(new java.awt.Color(255, 255, 255));
        menuItem_Quest.setText("Questionário");

        jMenuItem1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setText("Responder Questionário");
        menuItem_Quest.add(jMenuItem1);

        jMenuItem2.setText("Visualizar Respostas");
        menuItem_Quest.add(jMenuItem2);

        Menu.add(menuItem_Quest);

        menuItem_Devs.setForeground(new java.awt.Color(255, 255, 255));
        menuItem_Devs.setText("Desenvolvedores");
        Menu.add(menuItem_Devs);

        menuItem_Sair.setForeground(new java.awt.Color(255, 255, 255));
        menuItem_Sair.setText("Sair");
        menuItem_Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuItem_SairMouseClicked(evt);
            }
        });
        Menu.add(menuItem_Sair);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Workspace)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Workspace)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_LogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LogarActionPerformed
        // TODO add your handling code here:
        Logar login = new Logar();
        Workspace.add(login);
        login.setVisible(true);
        login.setPosicao();
        
    }//GEN-LAST:event_btn_LogarActionPerformed

    private void menuItem_SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItem_SairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItem_SairMouseClicked

    private void btn_QuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuestActionPerformed
        // TODO add your handling code here:
        frm1 frm = new frm1();
        Workspace.add(frm);
        frm.setVisible(true);
    }//GEN-LAST:event_btn_QuestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    public javax.swing.JDesktopPane Workspace;
    private javax.swing.JButton btn_Logar;
    private javax.swing.JButton btn_Quest;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu menuItem_Devs;
    private javax.swing.JMenu menuItem_Quest;
    private javax.swing.JMenu menuItem_Sair;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
